name: Build & Publish Image

on:
  release:
    types: [ created ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/mhitza/flake8-jupyter-notebook-github-action
  TAG_NAME: ${{ github.event.release.tag_name }}

jobs:
  release-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: set OVERRIDE_TAG_NAME
      run: echo OVERRIDE_TAG_NAME=$(echo ${{ env.TAG_NAME }} | grep -P -o "^v\d*[^.]") >> $GITHUB_ENV

    - name: Build & Publish
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }},${{ env.IMAGE_NAME }}:${{ env.OVERRIDE_TAG_NAME }}
