name: Smoke test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.ipynb'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mhitza/flake8-jupyter-notebook@v1
        with:
          debug: 'true'
